version: '3.8'

services:
  pdc:
    image: ${IMAGE_URL}
    build:
      context: .
    container_name: ${CONTAINER}
    restart: unless-stopped
    env_file:
      - ".env.local.yml"
    ports:
      - "0.0.0.0:7777:8080"

# - "0.0.0.0:${TARGET_LOCAL_PORT}:${TARGET_REMOTE_PORT}"
